version: '3'
services:
  triton_noetic:
    image: triton_noetic
    build: .
    volumes:
      - "/home/triton/Robotics_Triton_Project/catkin_ws/src:/catkin_ws/src"
    network_mode: host
    privileged: true
    devices:
      - /dev:/dev
    command: /bin/bash -c "tail -f /dev/null" 
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=192.168.1.102
